config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :invits, only: [:index, :show] do
    member do
      get :envoyer 
      get :relancer 
      get :valider 
      get :rejeter 
      get :confirmer 
      get :archiver
      post :validation
    end
    collection do
      post :action
    end
  end

  resources :formations
  resources :intervenants do
    member do
      get :invitations
      get :calendrier
    end
  end
  resources :users
  resources :fermetures
  resources :etudiants
  resources :documents
  resources :unites

  resources :cours do
    collection do
      get :planning, to: 'cours#index_slide'
      post :action
      post :action_do
    end
  end
    
  resources :salles do
    collection do
      get :occupation
      get :libres
    end
  end

  resources :dossiers do
    member do
      get :deposer
      get :envoyer
      get :valider
      get :rejeter
      get :relancer
      get :archiver
    end
  end

  resources :import_logs do
    member do
      get :download_imported_file
    end
  end

  resources :envoi_logs do
    member do
      get :activer
      get :tester
      get :suspendre
      get :annuler
    end
    collection do
      get :envoyer
    end
  end

  resources :mail_logs, only: %i[ index show ]

  namespace :tools do
    get :index

    get :import
    get :import_intervenants
    get :import_utilisateurs
    get :import_etudiants
    get :export
    get :export_intervenants
    get :export_utilisateurs
    get :export_etudiants
    get :export_formations
    get :export_vacations

    get :swap_intervenant
    get :etats_services
    get :audits
    get :taux_occupation_jours
    get :taux_occupation_salles
    get :nouvelle_saison
    get :notifier_intervenants
    get :creation_cours
    get :audit_cours
    get :liste_surveillants_examens
    get :rechercher
    get :rappel_des_cours
    get :acces_intervenants

    post :import_do
    post :creation_cours_do
    post :import_intervenants_do
    post :import_utilisateurs_do
    post :import_etudiants_do
    post :export_do
    post :export_intervenants_do
    post :export_utilisateurs_do
    post :export_etudiants_do
    post :export_formations_do
    post :export_vacations_do
    post :swap_intervenant_do
    post :taux_occupation_jours_do
    post :taux_occupation_salles_do
    post :nouvelle_saison_create
    post :notifier_intervenants_do
    post :rappel_des_cours_do
    post :acces_intervenants_do
  end

  get 'guide/index'
  
  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :cours
    end 

    namespace :v2 do 
        resources :cours do
          collection do
            get :in_progress
          end
        end
        resources :etudiants
    end 
  
    namespace :v3 do 
      resources :cours do
        collection do
          get :in_progress
        end
      end
    end 

    namespace :v4 do 
      resources :cours
    end 

  end 

  resources :alerts
  resources :ouvertures
  resources :agents

  get 'mentions_légales', to: 'pages#mentions_légales', as: :mentions_legales

  root 'cours#index'

end

app/models/dossier.rb
class Dossier < ApplicationRecord
  include Workflow
  include WorkflowActiverecord

  audited

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :intervenant

  has_many :documents, dependent: :destroy
  has_associated_audits

  accepts_nested_attributes_for :documents, 
                                allow_destroy:true, 
                                reject_if: lambda {|attributes| attributes['nom'].blank? }

  default_scope { order('dossiers.updated_at DESC') }                              
                              
  # WORKFLOW

  NOUVEAU = 'nouveau'
  ENVOYE  = 'envoyé'
  RELANCE1= 'relancé 1 fois'
  RELANCE2= 'relancé 2 fois'
  RELANCE3= 'relancé 3 fois'
  DEPOSE  = 'déposé'
  VALIDE  = 'validé'
  REJETE  = 'non_conforme'
  ARCHIVE = 'archivé'

  workflow do
    state NOUVEAU, meta: {style: 'badge-info'} do
      event :envoyer, transitions_to: ENVOYE
    end

    state ENVOYE, meta: {style: 'badge-primary'} do
      event :relancer, transitions_to: RELANCE1
      event :déposer, transitions_to: DEPOSE
    end

    state RELANCE1, meta: {style: 'badge-info'} do
      event :relancer, transitions_to: RELANCE2
      event :déposer, transitions_to: DEPOSE
    end

    state RELANCE2, meta: {style: 'badge-info'} do
      event :relancer, transitions_to: RELANCE3
      event :déposer, transitions_to: DEPOSE
    end
    
    state RELANCE3, meta: {style: 'badge-info'} do
      event :relancer, transitions_to: RELANCE1
      event :déposer, transitions_to: DEPOSE
    end
    
    state DEPOSE, meta: {style: 'badge-warning'} do
      event :valider, transitions_to: VALIDE
      event :rejeter, transitions_to: REJETE
    end

    state VALIDE, meta: {style: 'badge-success'} do
      event :archiver, transitions_to: ARCHIVE
    end

    state REJETE, meta: {style: 'badge-danger'} do
      event :déposer, transitions_to: DEPOSE
    end

    state ARCHIVE, meta: {style: 'badge-dark'}
  end

  # pour que le changement se voit dans l'audit trail
  def persist_workflow_state(new_value)
    self[:workflow_state] = new_value
    save!
  end
  
  def style
    self.current_state.meta[:style]
  end

  def self.périodes
    ['2021/2022','2022/2023','2023/2024','2024/2025', '2025/2026']
  end

  def self.xls_headers
    %w{ Id Nom Prénom Période Etat Mémo Documents Date_création Date_MAJ }
  end

  def self.to_xls(dossiers)
    require 'spreadsheet'    

    Spreadsheet.client_encoding = 'UTF-8'

    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet name: 'Dossiers_Candidatures_CEV'
    bold = Spreadsheet::Format.new :weight => :bold, :size => 11

    sheet.row(0).concat self.xls_headers
    sheet.row(0).default_format = bold

    index = 1
    dossiers.each do | dossier |
      fields_to_export = [
        dossier.id, 
        dossier.intervenant.nom,
        dossier.intervenant.prenom,
        dossier.période,
        dossier.workflow_state,
        dossier.mémo,
        dossier.documents.pluck(:nom, :workflow_state).join(', '),
        dossier.created_at, 
        dossier.updated_at
      ]
      sheet.row(index).replace fields_to_export
      index += 1
    end
    return book

  end
  
private

  # only one candidate for an nice id; one random UDID
  def slug_candidates
    [SecureRandom.uuid]
  end

end

app/controllers/dossiers_controller.rb
class DossiersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ show deposer]
  before_action :set_dossier, only: %i[ show edit update destroy envoyer deposer valider rejeter relancer archiver ]
  before_action :is_user_authorized

  layout :determine_layout

  # GET /dossiers or /dossiers.json
  def index
    authorize Dossier

    params[:période] ||= '2023/2024' 
    params[:order_by]||= 'dossiers.updated_at'

    if params[:archive].blank?
      @dossiers = Dossier.where.not(workflow_state: "archivé")
    else
      @dossiers = Dossier.all
    end
    
    unless params[:nom].blank?
      @dossiers = @dossiers.joins(:intervenant).where("intervenants.nom ILIKE ?", "%#{params[:nom].upcase}%")
    end 

    unless params[:période].blank?
      @dossiers = @dossiers.where(période: params[:période])
    end

    unless params[:workflow_state].blank?
      @dossiers = @dossiers.where("dossiers.workflow_state = ?", params[:workflow_state].to_s.downcase)
    end

    if params[:order_by] == 'intervenants.nom'
      @dossiers = @dossiers.joins(:intervenant).reorder(params[:order_by])
    end

    respond_to do |format|
      format.html do 
        @dossiers = @dossiers.paginate(page: params[:page], per_page: 20)
      end

      format.xls do
        book = Dossier.to_xls(@dossiers)
        file_contents = StringIO.new
        book.write file_contents # => Now file_contents contains the rendered file output
        filename = 'Dossiers_Candidatures_CEV.xls'
        send_data file_contents.string.force_encoding('binary'), filename: filename 
      end
    end

  end

  # GET /dossiers/1 or /dossiers/1.json
  def show
    #authorize @dossier
  end

  # GET /dossiers/new
  def new
    # Lister toutes les personnes ayant eu cours comme intervenant principal ou en binome
    période = '2023/2024'
    début_période = '2023-09-01'
    fin_période = '2024-08-31'

    # on garde les id des intervenants ayant eu cours sur la période
    intervenants_ids = Cour.where("DATE(cours.debut) BETWEEN ? AND ?", début_période, fin_période).pluck(:intervenant_id)
    # on y ajoute les intervenants ayants fait les cours comme binomes
    intervenants_ids += Cour.where("DATE(cours.debut) BETWEEN ? AND ?", début_période, fin_période).pluck(:intervenant_binome_id)
    # on ajoute les intervenants ayants fait des vacations
    intervenants_ids += Intervenant.where(id: Vacation.where("DATE(vacations.date) BETWEEN ? AND ?", début_période, fin_période).pluck(:intervenant_id))

    intervenants_avec_dossiers_sur_période = Dossier.where(période: période).pluck(:intervenant_id)

    @intervenants = Intervenant
                          .where("id IN(?)", intervenants_ids.uniq)
                          .where(status: 'CEV')
                          .where.not(id: intervenants_avec_dossiers_sur_période)
                          .uniq
    
    @dossier = Dossier.new
    @dossier.période = période
    3.times { @dossier.documents.build }
  end

  # GET /dossiers/1/edit
  def edit
    @intervenants = Intervenant.where(id: @dossier.intervenant)
  end

  # POST /dossiers or /dossiers.json
  def create
    @dossier = Dossier.new(dossier_params)

    respond_to do |format|
      if @dossier.save
        format.html { redirect_to @dossier, notice: "Nouveau dossier créé avec succès" }
        format.json { render :show, status: :created, location: @dossier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dossier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dossiers/1 or /dossiers/1.json
  def update
    respond_to do |format|
      if @dossier.update(dossier_params)
        format.html { redirect_to @dossier, notice: "Dossier modifié." }
        format.json { render :show, status: :ok, location: @dossier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dossier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dossiers/1 or /dossiers/1.json
  def destroy
    @dossier.destroy
    respond_to do |format|
      format.html { redirect_to dossiers_path, notice: "Dossier supprimé." }
      format.json { head :no_content }
    end
  end

  # 
  # WORKFLOW
  # 

  def envoyer
    # Passe le dossier à l'état 'Envoyé'
    @dossier.envoyer!

    # Informe l'intervenant
    mailer_response = DossierMailer.with(dossier: @dossier).dossier_email.deliver_now
    MailLog.create(user_id: current_user.id, message_id: mailer_response.message_id, to: @dossier.intervenant.email, subject: "Dossier de recrutement CEV (Envoyé)")

    redirect_to @dossier, notice: "Un email vient d'être envoyé à l'intervenant."
  end

  def deposer
    @dossier.déposer!
  end

  def valider
    # Valide tous les documents
    @dossier.documents.each do | doc |
      doc.valider! if doc.can_valider?
    end

    # Passe le dossier à l'état 'Validé'
    @dossier.valider!

    # Informe l'intervenant
    mailer_response = DossierMailer.with(dossier: @dossier).valider_email.deliver_now
    MailLog.create(user_id: current_user.id, message_id: mailer_response.message_id, to: @dossier.intervenant.email, subject: "Dossier de recrutement CEV (Validé)")

    redirect_to @dossier, notice: "Dossier validé avec succès. L'intervenant vient d'être informé."
  end

  def relancer
    # Passe le dossier à l'état 'Validé'
    @dossier.relancer!

    # Informe l'intervenant
    mailer_response = DossierMailer.with(dossier: @dossier).dossier_email.deliver_now
    MailLog.create(user_id: current_user.id, message_id: mailer_response.message_id, to: @dossier.intervenant.email, subject: "Dossier de recrutement CEV (Relancé)")

    redirect_to @dossier, notice: "Dossier relancé avec succès. L'intervenant vient d'être informé."
  end

  def rejeter
    # Vérifier qu'il y a au moins un document à l'état rejeté
    rejeter = false
    @dossier.documents.each do | doc |
      rejeter = true if doc.non_conforme?
    end
    
    if rejeter
      # Passe le dossier à l'état 'Rejeté'
      @dossier.rejeter!

      # Informe l'intervenant
      mailer_response = DossierMailer.with(dossier: @dossier).rejeter_email.deliver_now
      MailLog.create(user_id: current_user.id, message_id: mailer_response.message_id, to: @dossier.intervenant.email, subject: "Dossier de recrutement CEV (Rejeté)")


      redirect_to @dossier, notice: "Dossier rejeté. L'intervenant vient d'être informé."
    else
      redirect_to @dossier, alert: "Pour rejeter ce dossier, il faut qu'un document soit en statut 'Non_conforme' !"
    end
  end

  def archiver
    @dossier.documents.each do | doc |
      if doc.validé?
        doc.fichier.purge
        doc.archiver!
      elsif doc.non_conforme?
        doc.destroy
      end
    end
    @dossier.archiver!
    redirect_to @dossier, notice: 'Dossier archivé, les fichiers sources (PDF) des documents validés ont été supprimés'
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_dossier
      @dossier = Dossier.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dossier_params
      params.require(:dossier).permit(:intervenant_id, :période, :workflow_state, :mémo,
                                      documents_attributes: [:id, :nom, :fichier, :workflow_state, :commentaire])
    end

    def determine_layout
      'public' unless user_signed_in?
    end

    def is_user_authorized
      authorize Dossier
    end
end

app/helpers/dossiers_helper.rb
module DossiersHelper
end

app/views/dossiers/_form.html.erb
<%= bootstrap_form_with(model: dossier, local: true) do |form| %>
  <% if dossier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dossier.errors.count, "error") %> empêche ce dossier d'être enregistré :</h2>

      <ul>
        <% dossier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :intervenant_id %>

  <div class="row">
    <div class="col">
      <% if dossier.new_record? %>
        <%= form.select :période, options_for_select(Dossier.périodes, dossier.période) %>
      <% else %>
        <p>Période</p>
        
        <span class="form-control"><%= dossier.période %></span>
        <br>
        
      <% end %>
      <%= form.select :intervenant_id, 
                      options_from_collection_for_select(@intervenants, :id, :nom_prenom, @dossier.intervenant_id), 
                      class: 'form-control select2' %>

    </div>

    <div class="col">
      <%= form.select :workflow_state, Dossier.workflow_spec.states.keys.to_a, label: "Etat" %>
      <%= form.text_area :mémo %>
    </div>
  </div>

  <% unless dossier.new_record? %>
    <h5>Pièces justificatives</h5>
    <%= form.fields_for :documents do |doc| %>
      <div class="row shadow-sm">
        <div class="col-sm-3">
          <%= doc.text_field :nom %>
        </div>
        <div class="col-sm-2">
          <%= doc.select :workflow_state, Document.workflow_spec.states.keys.to_a, label: "Etat" %>
        </div>
        <div class="col">
          <%= doc.text_field :commentaire %>
        </div>
      </div>
    <% end %>
  <% end %>
  <br> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dossiers/deposer.html.erb
<br>
<p class="h3">
    Dossier déposé avec succès. Merci.
</p>
<br>

<p>
    Déposé le: <%= l DateTime.now.to_date %>
</p>

<p>
    Référence: <%= @dossier.slug %> 
</p>

<p class="alert alert-info">
    Votre gestionnaire va traiter votre dossier dans les meilleurs délais.
    Vous pouvez maintenant fermer cette fenêtre.
</p>

app/views/dossiers/edit.html.erb
<br>

<h1>Modification Dossier</h1>

<h3><%= @dossier.intervenant.nom_prenom %></h3>

<br>

<%= render 'form', dossier: @dossier %>

<%= link_to 'Voir', @dossier %> |
<%= link_to 'Retour', dossiers_path %>

app/views/dossiers/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <% if policy(Dossier).new? %>
    <%= link_to new_dossier_path, class: 'btn text-primary float-right' do %>
      <%= fa_icon 'plus-circle' %> Dossier
    <% end %>
  <% end %>
  <h3>
    <%= fa_icon 'folder' %> 
    Liste des dossiers de candidature 
  </h3>
</div>

<div class="container-fluid p-3 shadow-sm">
    <%= form_tag request.path, method: :get do %>
      <div class="form-group">
        <div class="row">

          <div class="col-sm-2">
            <%= label_tag :période, "Période" %>
            <%= select_tag :période, 
                                options_for_select(Dossier.périodes, params[:période]), 
                                include_blank: true,
                                class: 'form-control form-control-sm', 
                                onchange: 'this.form.submit()' %>
          </div>

          <div class="col-sm-3">
            <%= label_tag :nom, "Nom" %>    
            <%= text_field_tag :nom, params[:nom], include_blank:true, onchange:'this.form.submit()', class: 'form-control form-control-sm' %>
          </div>

          <div class="col-sm-2">
            <%= label_tag :workflow_state, "Etat" %>
            <%= select_tag :workflow_state, 
                                options_for_select(Dossier.workflow_spec.states.keys.to_a, params[:workflow_state]), 
                                include_blank: true,
                                class: 'form-control form-control-sm', 
                                onchange: 'this.form.submit()' %>
          </div>

          <div class="col-sm-2">
            <%= label_tag "Trier par " %>
            <br> 
            <%= radio_button_tag :order_by, 'dossiers.updated_at', (params[:order_by]=='dossiers.updated_at'), onchange:'this.form.submit()' %>
            Date MàJ 
            <%= radio_button_tag :order_by, 'intervenants.nom', (params[:order_by]=='intervenants.nom'), onchange:'this.form.submit()' %>
            Nom 
          </div>

          <div class="col-sm-3 mt-2">
            <br>
            <%= check_box_tag :archive, nil, params[:archive], onchange: 'this.form.submit()' %>
            <%= label_tag :archive, "Inclure les archivés ?" %>
          </div>
          
        </div>
      </div>  
    <% end %>
</div>
<br>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Période</th>
      <th>Intervenant</th>
      <th>Etat</th>
      <th>Création</th>
      <th>MàJ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dossiers.each do |dossier| %>
      <tr>
        <td><%= dossier.période %></td>
        <td><%= dossier.intervenant.nom_prenom %></td>
        <td>
          <span class="badge <%= dossier.style %>">
            <%= dossier.workflow_state.humanize %>
          </span>
          <% if dossier.envoyé? && (dossier.updated_at.to_date..Date.today).to_a.size >= 60 %>
            <%= fa_icon 'exclamation-circle' %>
          <% end %>
          <% if dossier.workflow_state == 'relancé 1 fois' && (dossier.updated_at.to_date..Date.today).to_a.size >= 15 %>
            <%= fa_icon 'exclamation-circle' %>
          <% end %>
          <% if dossier.workflow_state == 'relancé 2 fois' && (dossier.updated_at.to_date..Date.today).to_a.size >= 7 %>
            <%= fa_icon 'exclamation-circle' %>
          <% end %>
          <% if dossier.workflow_state == 'relancé 3 fois' && (dossier.updated_at.to_date..Date.today).to_a.size >= 3 %>
            <%= fa_icon 'exclamation-circle' %>
          <% end %>
        </td>
        <td><%= time_ago_in_words dossier.created_at %></td>
        <td><%= time_ago_in_words dossier.updated_at %></td>
        <td><%= link_to 'Voir', dossier %></td>
        <td><%= link_to 'Modifier', edit_dossier_path(dossier) %></td>
        <td><%= link_to '[X]', dossier, method: :delete, data: { confirm: 'Etes-vous bien certain.e ?' } %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr><th colspan=8></th></tr>
  </tfoot>
</table>

<div class="page_info">
  <%= page_entries_info @dossiers %>
  <%= @dossiers.reorder(nil).select(:id).group(:workflow_state).count(:id) %>
</div>

<%= will_paginate @dossiers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<br>
<%= link_to 'Export XLS', url_for(params.permit(:nom, :période, :workflow_state).merge(format: :xls)) %>

app/views/dossiers/new.html.erb
<h1>Nouveau Dossier</h1>
<br>

<%= render 'form', dossier: @dossier %>

<%= link_to 'Retour', dossiers_path %>

app/views/dossiers/show.html.erb
<br>

<p class="h3">
  <%= fa_icon 'folder' %>
  Dossier de candidature 
</p>
<br>

<div class="row shadow p-5">
  <div class="col-sm-4">
    <p>
      <strong>Intervenant:</strong>
      <%= @dossier.intervenant.nom_prenom %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @dossier.intervenant.email %>
    </p>

    <p>
      <strong>Période:</strong>
      <%= @dossier.période %>
    </p>

    <% if @dossier.validé? || @dossier.non_conforme? %>
      <p>
        <strong>Etat:</strong> 
        <span class="badge <%= @dossier.style %>">
          <%= @dossier.workflow_state.humanize %>
        </span>
      </p>
    <% end %>

    <% unless @dossier.mémo.blank? %>
      <p>
        <p class="alert alert-warning">
          <strong>Informations :</strong>
          <%= @dossier.mémo %>
        </p>
      </p>
    <% end %>

  </div>

  <div class="col">
    <h5>Pièces justificatives</h5>

    <% if @dossier.documents.any? %>
      <table class="table table-hover table-sm shadow-sm">
        <thead>
          <th>Type</th>
          <th>Fichier</th>
          <th>Etat</th>
          <th>MàJ il y a</th>
          <th></th>
        </thead>
        <tbody>
          <% @dossier.documents.each do | doc | %>
            <tr>
              <td><%= doc.nom %></td>
              <td>
                <% if doc.fichier.attached? %>
                <%= link_to doc.fichier.filename, url_for(doc.fichier), target: '_blank' %>
                <% end %>
              </td>
              <td>
                 <span class="badge <%= doc.style %>">
                  <%= doc.workflow_state.humanize %>
                </span>
                <% if doc.non_conforme? %>
                  <br>
                  <b><%= "Motif: #{ doc.commentaire }" %></b>
                <% end %>
              </td>
              <td><%= time_ago_in_words(doc.created_at) %></td>
              <td><%= link_to_if @dossier.can_déposer?, '[X]', doc, method: :delete, data: { confirm: 'Etes-vous bien certain.e ?' } %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr><th colspan=5></th></tr>
        </tfoot>
      </table>
    <% else %>
      <% if current_user %>
        <p>
          Aucun document pour l'instant.
        </p>
      <% else %>
        <p class="alert alert-warning">
          <br>
          Veuillez ajouter les justificatifs correspondants à votre situation 
          (voir le document 'Pièces à fournir.pdf') en utilisant le bouton
          <%= link_to new_document_path(dossier_id: @dossier.id), data: { toggle: "modal", target: "#myModal" }, class: 'btn btn-link' do %>
            <%= fa_icon 'plus-circle' %> Ajouter un document
          <% end %>
          <br>

          Quand le dossier est complet et prêt à être déposé, cliquez sur 'Déposer le dossier'.
          <br><br>
        </p>
      <% end %>
    <% end %>

    <%= link_to new_document_path(dossier_id: @dossier.id), data: { toggle: "modal", target: "#myModal" }, class: 'btn btn-link' do %>
      <%= fa_icon 'plus-circle' %> Ajouter un document
    <% end %>

  </div>
</div>

<% if current_user %>
  <br>
  <%= link_to 'Modifier', edit_dossier_path(@dossier) %> |
  <%= link_to_if @dossier.can_envoyer?, 'Envoyer', envoyer_dossier_path(@dossier), title: "Envoyer un mail à l'intervenant contenant un lien unique vers son dossier", class: 'btn btn-sm btn-primary' %> |
  <%= link_to_if @dossier.can_valider?, 'Valider', valider_dossier_path(@dossier), class: 'btn btn-sm btn-success' %> |
  <%= link_to_if @dossier.can_rejeter?, 'Rejeter', rejeter_dossier_path(@dossier), class: 'btn btn-sm btn-danger' %> |
  <%= link_to_if @dossier.can_relancer?, 'Relancer', relancer_dossier_path(@dossier), class: 'btn btn-sm btn-info' %> |
  <%= link_to_if @dossier.can_archiver?, 'Archiver', archiver_dossier_path(@dossier), class: 'btn btn-sm btn-secondary' %> |
  <%= link_to 'Retour', dossiers_path %>
  <br>
<% else %>
  <% if @dossier.can_déposer? %>
    <br>
    <%= link_to deposer_dossier_path(dossier_id: @dossier.id), data: { confirm: 'Etes-vous bien certain.e de vouloir déposer ce dossier ?' }, class: "btn btn-success #{ 'disabled' unless @dossier.documents.any? }" do %>
      <%= fa_icon 'arrow-circle-up' %> Déposer le dossier
    <% end %>

    <br><br>
  <% end %>

<% end %>
<br>


<% if policy(@dossier).audits? %>
  <br>
  <h5>Audit des modifications</h5>

  <table class="table table-hover table-sm table-striped table-bordered">
    <thead>
      <th>Date</th>
      <th>Utilisateur</th>            
      <th>Type</th>
      <th>Id</th>
      <th>Action</th>
      <th>Modifications</th>
    </thead>
    <%= render partial: 'tools/audit', collection: @dossier.own_and_associated_audits %>
  </table>
  <br>
<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Ajout d'un document</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= render 'documents/modal_form', document: Document.new(dossier_id: @dossier.id) %>
      </div>
    </div>
  </div>
</div>