config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :invits, only: [:index, :show] do
    member do
      get :envoyer 
      get :relancer 
      get :valider 
      get :rejeter 
      get :confirmer 
      get :archiver
      post :validation
    end
    collection do
      post :action
    end
  end

  resources :formations
  resources :intervenants do
    member do
      get :invitations
      get :calendrier
    end
  end
  resources :users
  resources :fermetures
  resources :etudiants
  resources :documents
  resources :unites

  resources :cours do
    collection do
      get :planning, to: 'cours#index_slide'
      post :action
      post :action_do
    end
  end
    
  resources :salles do
    collection do
      get :occupation
      get :libres
    end
  end

  resources :dossiers do
    member do
      get :deposer
      get :envoyer
      get :valider
      get :rejeter
      get :relancer
      get :archiver
    end
  end

  resources :import_logs do
    member do
      get :download_imported_file
    end
  end

  resources :envoi_logs do
    member do
      get :activer
      get :tester
      get :suspendre
      get :annuler
    end
    collection do
      get :envoyer
    end
  end

  resources :mail_logs, only: %i[ index show ]

  namespace :tools do
    get :index

    get :import
    get :import_intervenants
    get :import_utilisateurs
    get :import_etudiants
    get :export
    get :export_intervenants
    get :export_utilisateurs
    get :export_etudiants
    get :export_formations
    get :export_vacations

    get :swap_intervenant
    get :etats_services
    get :audits
    get :taux_occupation_jours
    get :taux_occupation_salles
    get :nouvelle_saison
    get :notifier_intervenants
    get :creation_cours
    get :audit_cours
    get :liste_surveillants_examens
    get :rechercher
    get :rappel_des_cours
    get :acces_intervenants

    post :import_do
    post :creation_cours_do
    post :import_intervenants_do
    post :import_utilisateurs_do
    post :import_etudiants_do
    post :export_do
    post :export_intervenants_do
    post :export_utilisateurs_do
    post :export_etudiants_do
    post :export_formations_do
    post :export_vacations_do
    post :swap_intervenant_do
    post :taux_occupation_jours_do
    post :taux_occupation_salles_do
    post :nouvelle_saison_create
    post :notifier_intervenants_do
    post :rappel_des_cours_do
    post :acces_intervenants_do
  end

  get 'guide/index'
  
  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :cours
    end 

    namespace :v2 do 
        resources :cours do
          collection do
            get :in_progress
          end
        end
        resources :etudiants
    end 
  
    namespace :v3 do 
      resources :cours do
        collection do
          get :in_progress
        end
      end
    end 

    namespace :v4 do 
      resources :cours
    end 

  end 

  resources :alerts
  resources :ouvertures
  resources :agents

  get 'mentions_légales', to: 'pages#mentions_légales', as: :mentions_legales

  root 'cours#index'

end

app/helpers/tools_helper.rb
module ToolsHelper

    # Rendre l'audit lisible 

    def prettify(audit)    

        pretty_changes = []
        
        audit.audited_changes.each do |c|
            key = c.first.humanize
            case key
            when 'Salle'
                if salle = convertir_id_salles(audit)
                    pretty_changes << salle
                end
            when 'Formation'
                ids = audit.audited_changes['formation_id']
                case ids.class.name
                when 'Integer'
                    pretty_changes << "#{key} initialisée à '#{Formation.unscoped.find(ids).nom}'"
                when 'Array'
                    if ids.first && ids.last 
                        pretty_changes << "#{key} changée de '#{Formation.unscoped.find(ids.first).nom}' à '#{Formation.unscoped.find(ids.last).nom}'"
                    elsif ids.first 
                        pretty_changes << "#{key} changée de '#{Formation.unscoped.find(ids.first).nom}' à 'nil'"
                    else
                        pretty_changes << "#{key} changée de 'nil' à '#{Formation.unscoped.find(ids.last).nom}'"
                    end
                end 
            when 'Intervenant'
                ids = audit.audited_changes['intervenant_id']
                case ids.class.name
                when 'Integer'
                    pretty_changes << "#{key} initialisé à '#{Intervenant.find(ids).nom_prenom}'"
                when 'Array'
                    pretty_changes << "#{key} changé de '#{Intervenant.find(ids.first).nom_prenom}' à '#{Intervenant.find(ids.last).nom_prenom}'"
                end 
            when 'User'
                ids = audit.audited_changes['user_id']
                if User.exists?(id: ids)
                    case ids.class.name
                    when 'Integer'
                        pretty_changes << "#{key} initialisé à '#{User.find(ids).nom_et_prénom}'"
                    when 'Array'
                        pretty_changes << "#{key} changé de '#{User.find(ids.first).nom_et_prénom if ids.first}' à '#{User.find(ids.last).nom_et_prénom if ids.last}'"
                    end 
                else
                    pretty_changes << "Utilisateur supprimé"
                end
            when 'Debut' 
                if audit.audited_changes['debut'].class.name == 'Array'
                    pretty_changes << "Horaire de début modifié de '#{I18n.l(c.last.first, format: :long)}' à '#{I18n.l(c.last.last, format: :long)}'"
                else
                    pretty_changes << "Début initialisé à '#{I18n.l(c.last, format: :long)}'"
                end
            when 'Fin' 
                if audit.audited_changes['fin'].class.name == 'Array'
                    pretty_changes << "Horaire de fin modifié de '#{I18n.l(c.last.first, format: :long)}' à '#{I18n.l(c.last.last, format: :long)}'"
                else
                    pretty_changes << "Fin initialisée à '#{c.last}'"
                end
            when 'Etat'
                if audit.audited_changes['etat'].class.name == 'Array'
                    begin
                        pretty_changes << "État modifié de '#{ Cour.etats.keys[c.last.first].humanize if c.last.first }' à '#{ Cour.etats.keys[c.last.last].humanize if c.last.last }'"
                    rescue => e
                        pretty_changes << "/!\\ PB avec les données à convertir !"
                    end
                elsif audit.audited_changes['etat'].class.name == 'Integer'
                    pretty_changes << "État initialisé à '#{ Cour.etats.keys[c.last].humanize }'"
                else
                    pretty_changes << "État initialisé à '#{ c.last.humanize }'"
                end
            else
                if audit.action == 'update'
                    unless c.last.first.blank? && c.last.last.blank?    
                        pretty_changes << "#{key} modifié de '#{c.last.first}' à '#{c.last.last}'"
                    end
                else 
                    unless c.last.blank?
                        pretty_changes << "#{key} #{audit.action == 'create' ? 'initialisé à' : 'était'} '#{c.last}'"
                    end
                end
            end
        end
        pretty_changes
    end

    def audited_view_path(audit)
        case audit.auditable_type
        when "Cour"
            if Cour.exists?(audit.auditable_id)
                cour_path(audit.auditable_id)
            end
        when "User"
            if User.exists?(audit.auditable_id)
                user_path(audit.auditable_id)
            end
        when "Formation"
            if Formation.exists?(audit.auditable_id)
                formation_path(audit.auditable_id)
            end
        when "Intervenant"
            if Intervenant.exists?(audit.auditable_id)
                intervenant_path(audit.auditable_id)
            end
        when "Etudiant"
            if Etudiant.exists?(audit.auditable_id)
                etudiant_path(audit.auditable_id)
            end
        when "Salle"
            if Salle.exists?(audit.auditable_id)
                salle_path(audit.auditable_id)
            end
        when "Fermeture"
            if Fermeture.exists?(audit.auditable_id)
                fermeture_path(audit.auditable_id)
            end
        end
    end

    def convertir_id_salles(audit)
        # Rendre l'audit lisible quand changement de salle (nom des salles au lieu des id) 

        if audit.audited_changes.include?('salle_id') && audit.action != 'destroy'
            salle_id = audit.audited_changes['salle_id'] 
            if salle_id.class.name == 'Array' 
                if salle_id_was = salle_id.first 
                    salle_before = Salle.with_discarded.find(salle_id_was).nom 
                end 
                if salle_id = salle_id.last 
                    salle_after = Salle.with_discarded.find(salle_id).nom 
                end 
                if salle_before
                    return "Salle changée de '#{salle_before}' à '#{salle_after}'"
                else
                    return "Cours mis en salle '#{salle_after}"
                end
            else 
                if salle_id.class.name == 'Integer' 
                    salle_after = Salle.with_discarded.find(salle_id).nom 
                else 
                    salle_after = salle_id 
                end
                return "Salle initialisée à '#{salle_after}'"
            end  
        end 
    end

    def extract_salle_id(audit)
        # extraire l'id de la salle dans une ligne d'audit
        k = audit.audited_changes['salle_id']
        case k.class.name
        when 'Array'
            return k.last 
        when 'Integer'
            return k 
        else
            return nil
        end    
    end

end

app/views/tools/audit_cours.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'calendar-check' %> Liste des cours "à booker" </h3>
  <p>
    Liste des cours récemment planifiés (sans salle) et à confirmer.
  </p>
</div>

<%= form_tag request.path, method: :get do %>
    <div class="form-group">
        <div class="row">

            <div class="col-sm-3">
                <%= label_tag "Période du" %>    
                <%= text_field_tag :start_date, params[:start_date], type:'date', class:"form-control" %>
            </div>

            <div class="col-sm-3">
                <%= label_tag "au" %>    
                <%= text_field_tag :end_date, params[:end_date], type:'date', class:"form-control", onchange:'this.form.submit()' %>
            </div>

            <div class="col-sm-3">
                <p>Trier par</p>

                <div class="form-check-inline">
                    <label class="form-check-label">
                        <%= radio_button_tag :tri, :date_cours, params[:tri] == 'date_cours', class: "form-check-input", onchange:'this.form.submit()' %>
                        Date du cours
                    </label>
                </div>

                <div class="form-check-inline">
                    <label class="form-check-label">
                        <%= radio_button_tag :tri, :date_création, params[:tri] == 'date_création' , class: "form-check-input", onchange:'this.form.submit()' %>
                        Date de création
                    </label>
                </div>

            </div>

        </div>
    </div>
<% end %>

<table class="table table-hover table-sm">
    <thead class="shadow-sm">
        <tr>    
            <th>Semaine</th>
            <th>Date</th>
            <th>Heure</th>
            <th>Formation</th>
            <th>Intervenant</th>
            <th colspan="2">UE/Intitulé du cours</th>
            <th>Etat</th>
            <th>Depuis</th>
            <th>Par</th>
            <th></th>
        </tr>
    </thead>

    <% @cours.each do | cours | %>
        <tr class="shadow-sm">
            <td class="text-center">
                <%= link_to cours_url(start_date: cours.debut.to_date.beginning_of_week, view: 'calendar_rooms'), target: '_blank' do %>
                    <%= cours.debut.to_date.strftime('%-V') %>
                <% end %>
            </td>
            <td>
                <h5>
                    <% color = 'warning' if (cours.debut.to_date - Date.today) <= 30 %>
                    <% color = 'danger' if (cours.debut.to_date - Date.today) <= 7 %>
                    <span class="badge badge-pill badge-<%= color %>">
                        <b><%= l cours.debut.to_date %></b>
                    </span>
                </h5>
            </td>
            <td>
                <b><%= l(cours.debut, format: :heures_min) %></b> 
                <%= l(cours.fin, format: :heures_min) %>
            </td>
            <td>
                <span style="background-color:<%= cours.formation.color %>;padding-left: 7px;margin-right: 5px;"></span>
                <%= link_to cours.formation.nom_nbr_etudiants, cours.formation %>
            </td>
            <td>
                <%= cours.intervenant.nom_prenom %>
                <% if cours.intervenant_binome %>
                    <br>
                    <%= cours.intervenant_binome.nom_prenom %>
                <% end %>
            </td>
            <td>
                <%= cours.try(:ue) %>
            </td>
            <td>
                <%= cours.nom_ou_ue %>
            </td>
            <td style="white-space: nowrap;">
                <%= cours.etat.humanize %>

                <% unless cours.commentaires.blank? %>
                    <%= fa_icon 'comment-dots' %>         
                    <%= cours.commentaires %>
                <% end %>
            </td>

            <td style="white-space: nowrap;">                
                <%= time_ago_in_words cours.audits.first.created_at %>
            </td>

            <td>
                <%= cours.audits.first.user.nom_et_prénom %>
            </td>
            
            <td>
                <%= link_to edit_cour_path(cours), target: '_blank', class: "btn btn-outline-light text-dark" do %>
                    <%= fa_icon 'edit '%>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>

<%= "Affichage de #{ @cours.length } cours au total" %>
<br>

app/views/tools/creation_cours.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'calendar-alt' %> Réservation de créneaux horaires</h3>
</div>
<br>

<%= form_tag({action: "creation_cours_do", method: :post}, multipart: true) do %>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-7">
        <%= label_tag :debut, "A partir du", class:"font-weight-bold"  %><br>
        <%= datetime_select :cours, :start_date, minute_step:15 %>
        <br><br>

        <%= label_tag :fin, "Jusqu'au", class:"font-weight-bold"  %><br>
        <%= date_select :cours, :end_date %>
        <br><br>

        <%= label_tag :semaines, "Semaines *", class:"font-weight-bold"  %>
        <%= select_tag :semaines, options_for_select((1..52).to_a), 
                          include_blank:true, multiple:true, class:"form-control" %>
        <br>

        <div class="field">
          <%= label_tag :jours, nil, class:"font-weight-bold"  %><br>
          <%= check_box_tag :lundi, '1', params[:lundi] %> Lundi 
          <%= check_box_tag :mardi, '1', params[:mardi] %> Mardi 
          <%= check_box_tag :mercredi, '1', params[:mercredi] %> Mercredi
          <%= check_box_tag :jeudi,  '1', params[:jeudi] %> Jeudi
          <%= check_box_tag :vendredi, '1', params[:vendredi] %> Vendredi
          <%= check_box_tag :samedi,  '1', params[:samedi] %> Samedi
        </div>
        <br>
  
        <section id="période">
          <%= label_tag :periode, "Période", class:"font-weight-bold" %><br>
          <div class="row">
            <div class="col">
              Matin
              <br>
              <%= check_box_tag :am, '1', params[:am] %> 9h-12h
            </div>
            
            <div class="col">
              Après-midi
              <br>
              <%= check_box_tag :pm, '1', params[:pm] %> 13h-16h
            </div>
            <div class="col">
              Soir
              <br>
              <%= check_box_tag :soir_params, '1', params[:soir_params] == 1 %> 19h-22h
              <br>
              <%= check_box_tag :soir_params, '2', params[:soir_params] == 2 %> 18h15-20h15
              <br>
              <%= check_box_tag :soir_params, '3', params[:soir_params] == 3 %> 20h15-22h15
            </div>
            <div class="col">
              Autre
              <br>
              <%= check_box_tag :other, '1', params[:other] %> Durée:
              <br>
              <%= select_tag :duree, 
                              options_for_select([0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0], 3.0), 
                              include_blank:true %> h
            </div>
          </div>
        </section>
      </div>

      <div class="col-sm-5">
        <div class="row">

        <%= label_tag :formation_id, "Formation", class:"font-weight-bold"  %>
        <%= select_tag :formation_id, 
              options_from_collection_for_select(Formation.all, :id, :nom_promo), class:"form-control select2", include_blank:true %>
        <br>

        <%= label_tag :intervenant_id, "Intervenant", class:"font-weight-bold"  %>
        <%= select_tag :intervenant_id,
              options_from_collection_for_select(Intervenant.all, :id, :nom_prenom), class:"form-control select2", include_blank:true %>
        <br>

        <%= label_tag :nom, "Nom du cours *", class:"font-weight-bold"  %>
        <%= text_field_tag :nom, params[:nom], class:"form-control" %>
        <br>

        <%= label_tag :code_ue, "UE *", class:"font-weight-bold"  %>
        <%= number_field :code_ue, params[:code_ue], class:"form-control" %>
        <br>

        <%= label_tag :salle_id, "Salle *", class:"font-weight-bold"  %>
        <%= select_tag :salle_id, options_from_collection_for_select(Salle.all, :id, :nom_places, params[:salle_id]), include_blank: true, class:"form-control" %>
        * Optionnel
        <br><br>

        <div class="field">
          <strong class="lead font-weight-bold">Enregistrer les changements ?</strong> <br>
          <%= label :save, "Oui", :value => "true" %>
          <%= radio_button_tag :save, true %>
          <%= label :save, "Non", :value => "false" %>
          <%= radio_button_tag :save, false, :checked => true %>
          <br><i>Choisissez 'Non' pour tester votre création car <b>elle est irréversible !</b></i><br />
        </div>
        <br><br><br><br>
      
        <div class="actions">
          <%= submit_tag "Lancer la création", class: "btn btn-success mt-5" %>
        </div>

      </div>
  </div>
  
<% end %>

app/views/tools/creation_cours_do.html.erb
<h3>
	Réservation de créneaux horaires du <%= l(@start_date) %> au <%= l(@end_date) %>
</h3>
<br>


<pre>
	<%= simple_format(@stream) %>
</pre>

app/views/tools/export_etudiants_do.csv.erb
<%= @csv_string.html_safe %>

app/views/tools/export_intervenants.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'upload' %> Export des intervenants </h3>
</div>
<br>

<div>
  <h3>Cette fonction permet la création d'une feuille Excel contenant tous les intervenants</h3>
</div>

<%= form_tag({action: "export_intervenants_do", method: :post}) do %>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :date_debut, "Intervenus du" %>
        <%= text_field_tag :date_debut, params[:date_debut], type: 'date', class: 'form-control', required: true %>
      </div>

      <div class="col-sm-2">
        <%= label_tag :date_fin, "au" %>
        <%= text_field_tag :date_fin, params[:date_fin], type: 'date', class: 'form-control', required: true %>
      </div>

      <div class="col-sm-3">
          <%= label_tag :status, "Statut" %>
          <%= select_tag :status, 
                options_for_select(Intervenant.statuses, params[:status]), 
                include_blank:true,
                class: 'form-control' %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-2">
        <div class="actions">
          <%= submit_tag "Exporter", class: "btn btn-success" %>
        </div>
      </div>
    </div> 

  </div>
  
<% end %>

app/views/tools/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'wrench' %> Outils</h3>
</div>
<br>

<div class="row">
	<div class="col-sm-4">
		<ul>
			<li>
				<%= fa_icon 'calendar-day' %>
				<%= link_to "Réservation de créneaux horaires", tools_creation_cours_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'tv' %>
				<%= link_to "Planning au format 'téléviseur'", planning_cours_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'tv' %>
				<small><%= fa_icon 'asterisk' %></small>
				<%= link_to "Nouveau Planning TV (version bêta)", "https://tableau-affichage-horaires-iae.herokuapp.com/", target: "_blank" %>
			</li>
			<br>

			<li>
				<%= fa_icon 'tachometer-alt' %>
				<%= link_to "Taux d'occupation jours", tools_taux_occupation_jours_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'tachometer-alt' %>
				<%= link_to "Taux d'occupation salles", tools_taux_occupation_salles_path %>
			</li>
			<br>
			<br>
			<% if current_user.rh? || current_user.admin? %>
				<li>
					<%= fa_icon 'list-alt' %>
					<%= link_to "Etats de services", tools_etats_services_path %>
				</li>
				<br>
				<li>
					<%= fa_icon 'list-alt' %>
					<%= link_to "Liste des surveillances d'examens", tools_liste_surveillants_examens_path %>
				</li>
				<br>
				<li>
					<%= fa_icon 'user-secret' %>
					<%= link_to "Agents", agents_path %>
				</li>
				<br>
				<br>
			<% end %>

			<% if current_user.role_number >= 5 %>
				<li>
					<%= fa_icon 'calendar-check' %>
					<%= link_to 'Invitations', invits_path %>
				</li>
			<% end %>
			<br>
			<li>
				<%= fa_icon 'envelope' %>
				<%= link_to 'MailLogs', mail_logs_path %>
			</li>

		</ul>
	</div>
	
	<div class="col-sm-4">
		<ul>
			<li>
				<%= fa_icon 'download' %>
				<%= link_to "Import de cours", tools_import_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'download' %>
				<%= link_to "Import d'intervenants", tools_import_intervenants_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'download' %>
				<%= link_to "Import d'étudiants", tools_import_etudiants_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'inbox' %>
				<%= link_to "Import log", import_logs_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'upload' %>
				<%= link_to "Export de cours", tools_export_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'upload' %>
				<%= link_to "Export des intervenants", tools_export_intervenants_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'upload' %>
				<%= link_to "Export d'étudiants", tools_export_etudiants_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'upload' %>
				<%= link_to "Export des formations", tools_export_formations_path %>
			</li>
			<br>

			<li>
				<%= fa_icon 'upload' %>
				<%= link_to "Export des vacations", tools_export_vacations_path %>
			</li>
			<br><br>

			<li>
				<%= fa_icon 'key' %>
				<%= link_to "Créer accès intervenant", tools_acces_intervenants_path %>
			</li>
			<br>
		</ul>
	</div>

	<% if current_user.admin? %>
		<div class="col-sm-4">
			<ul>
				<li>
					<%= fa_icon 'users' %>
					<%= link_to "Utilisateurs", users_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'download' %>
					<%= link_to "Import des utilisateurs", tools_import_utilisateurs_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'upload' %>
					<%= link_to "Export des utilisateurs", tools_export_utilisateurs_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'random' %>
					<%= link_to "Intervertir deux intervenants", tools_swap_intervenant_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'search' %>
					<%= link_to "Audit des modifications", tools_audits_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'chalkboard' %>
					<%= link_to "Salles", salles_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'calendar' %>
					<%= link_to "Nouvelle saison", tools_nouvelle_saison_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'bell' %>
					<%= link_to "Rappel des cours (file d'attente)", envoi_logs_path %>
				</li>
				<br>


				<li>
					<%= fa_icon 'search' %>
					<%= link_to 'Audit des cours récemment planifiés', tools_audit_cours_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'umbrella-beach' %>
					<%= link_to "Jours de fermeture", fermetures_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'business-time' %>
					<%= link_to "Horaires d'ouverture", ouvertures_path %>
				</li>
				<br>

				<li>
					<%= fa_icon 'exclamation' %>
					<%= link_to "Alertes", alerts_path %>
				</li>

			</ul>
		</div>
	<% end %>

</div>

app/views/tools/nouvelle_saison_create.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2>
    <%= fa_icon 'calendar' %> Réservations en masse
    <br>
    <small>Réservation de créneaux horaires sur toute une année scolaire</small>
  </h2>
</div>
<br>

<% if @errors.any? %>
  <% @errors.each do |error| %>
    <b><%= l(error.first, format: :perso) %></b>
    <%= simple_format error.last[:cours].last %>
  <% end %>
  <br>
<% end %>

<% if @ids_ok.any? %>
  <%= link_to 'Afficher les cours créés', cours_path(ids: @ids_ok) %>
<% end %>

app/views/tools/rechercher.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'search-plus' %> Chercher</h3>
</div>

<div class="container-fluid p-3 shadow-sm">
  <%= form_tag tools_rechercher_path, method: :get do %>
    <div class="form-group">
      <div class="row mb-3 px-3">
        <%= label_tag :nom, "Entrez un terme à rechercher dans toute l'application" %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], include_blank:true, onchange:'this.form.submit()', class:"form-control form-control-sm" %>
          <span class="input-group-btn">
            <%= button_tag name: 'commit', value: 'Go', class: "btn btn-sm btn-success ml-1" do %>
              <%= fa_icon 'search-plus' %>
            <% end %>
          </span>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <span>
            Inclure :
          </span>
          <%= check_box_tag :search_cours, '1', params[:search_cours] == '1' %>
          <%= label_tag "Cours" %>
        </div>
        <div class="col">
          <%= check_box_tag :search_formations, '1', params[:search_formations] == '1' %>
          <%= label_tag "Formations" %>
        </div>
        <div class="col">
          <%= check_box_tag :search_intervenants, '1', params[:search_intervenants] == '1' %>
          <%= label_tag "Intervenants" %>
        </div>
        <div class="col">
          <%= check_box_tag :search_etudiants, '1', params[:search_etudiants] == '1' %>
          <%= label_tag "Étudiants" %>
        </div>
        <div class="col">
          <%= check_box_tag :search_users, '1', params[:search_users] == '1' %>
          <%= label_tag "Utilisateurs" %>
        </div>
        <div class="col-1">
          <%= check_box_tag :search_ue, '1', params[:search_ue] == '1' %>
          <%= label_tag :ue, "U.E." %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if defined?(@results) %>
  <% if @results.any? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Type</th>
          <th>Contenu</th>
          <th>Voir</th>
          <th>MÀJ</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: @results, as: :result %>
      </tbody>
      <tfoot>
        <tr><th colspan=4></th></tr>
      </tfoot>
    </table>
    <div class="page_info">
      <%= page_entries_info @results %>
    </div>
    <%= will_paginate @results, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <br>
  <% else %>
    <p class="title is-4 has-text-centered p-6">
      Aucun résultat trouvé...
    </p>
  <% end %>
<% end %>