config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :invits, only: [:index, :show] do
    member do
      get :envoyer 
      get :relancer 
      get :valider 
      get :rejeter 
      get :confirmer 
      get :archiver
      post :validation
    end
    collection do
      post :action
    end
  end

  resources :formations
  resources :intervenants do
    member do
      get :invitations
      get :calendrier
    end
  end
  resources :users
  resources :fermetures
  resources :etudiants
  resources :documents
  resources :unites

  resources :cours do
    collection do
      get :planning, to: 'cours#index_slide'
      post :action
      post :action_do
    end
  end
    
  resources :salles do
    collection do
      get :occupation
      get :libres
    end
  end

  resources :dossiers do
    member do
      get :deposer
      get :envoyer
      get :valider
      get :rejeter
      get :relancer
      get :archiver
    end
  end

  resources :import_logs do
    member do
      get :download_imported_file
    end
  end

  resources :envoi_logs do
    member do
      get :activer
      get :tester
      get :suspendre
      get :annuler
    end
    collection do
      get :envoyer
    end
  end

  resources :mail_logs, only: %i[ index show ]

  namespace :tools do
    get :index

    get :import
    get :import_intervenants
    get :import_utilisateurs
    get :import_etudiants
    get :export
    get :export_intervenants
    get :export_utilisateurs
    get :export_etudiants
    get :export_formations
    get :export_vacations

    get :swap_intervenant
    get :etats_services
    get :audits
    get :taux_occupation_jours
    get :taux_occupation_salles
    get :nouvelle_saison
    get :notifier_intervenants
    get :creation_cours
    get :audit_cours
    get :liste_surveillants_examens
    get :rechercher
    get :rappel_des_cours
    get :acces_intervenants

    post :import_do
    post :creation_cours_do
    post :import_intervenants_do
    post :import_utilisateurs_do
    post :import_etudiants_do
    post :export_do
    post :export_intervenants_do
    post :export_utilisateurs_do
    post :export_etudiants_do
    post :export_formations_do
    post :export_vacations_do
    post :swap_intervenant_do
    post :taux_occupation_jours_do
    post :taux_occupation_salles_do
    post :nouvelle_saison_create
    post :notifier_intervenants_do
    post :rappel_des_cours_do
    post :acces_intervenants_do
  end

  get 'guide/index'
  
  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :cours
    end 

    namespace :v2 do 
        resources :cours do
          collection do
            get :in_progress
          end
        end
        resources :etudiants
    end 
  
    namespace :v3 do 
      resources :cours do
        collection do
          get :in_progress
        end
      end
    end 

    namespace :v4 do 
      resources :cours
    end 

  end 

  resources :alerts
  resources :ouvertures
  resources :agents

  get 'mentions_légales', to: 'pages#mentions_légales', as: :mentions_legales

  root 'cours#index'

end

app/models/formation.rb
class Formation < ApplicationRecord
	include PgSearch::Model
	multisearchable against: [:nom]

	audited
	
	has_many :users
	has_many :cours, dependent: :destroy
	has_many :intervenants, through: :cours
	has_many :unites
	accepts_nested_attributes_for :unites, allow_destroy:true, 
									reject_if: lambda {|attributes| attributes['code'].blank?}
	has_many :etudiants
	accepts_nested_attributes_for :etudiants, allow_destroy:true, 
									reject_if: lambda {|attributes| attributes['nom'].blank?}
	has_many :vacations
	accepts_nested_attributes_for :vacations, allow_destroy:true, 
									reject_if: lambda {|attributes| attributes['intervenant_id'].blank? || 
																	attributes['titre'].blank? ||
																	attributes['date'].blank? ||
																	attributes['qte'].blank? ||
																	attributes['forfaithtd'].blank?	}
	belongs_to :user

	validates :nom, :nbr_etudiants, :nbr_heures, :abrg, presence: true
	validates :nom, uniqueness: { scope: :promo }
	
	default_scope { where("archive is null OR archive is false") }
	default_scope { order(:nom, :promo) } 
	
	def nom_promo
		self.promo.blank? ? self.nom : "#{self.nom} - #{self.promo}" 
	end

	def nom_promo_full
		self.promo.blank? ? self.nom : "#{self.nom} | Promo: #{self.promo}" 
	end

	def nom_promo_etudiants
		self.promo.blank? ? "#{self.nom} (#{self.nbr_etudiants}E)"  : "#{self.nom} - #{self.promo} (#{self.nbr_etudiants}E)" 
	end

	def nom_nbr_etudiants
		"#{self.nom} (#{self.nbr_etudiants} ET.)" 
	end

	def nom_abrg_nbr_etudiants
		"#{self.abrg} (#{self.nbr_etudiants} ET.)" 
	end

	def nom_eotp
		self.code_analytique.blank? ? self.nom : "#{self.nom} -> #{self.code_analytique}"
	end

	def code_analytique_avec_indice(date)
		code = self.code_analytique || ''
		if code.last == '?'
			indice = ((date.year - self.cours.first.debut.year) + 1)
			# renvoie '_' si l'indice dépasse la limite de 3 années (cursus normal)
			return code.gsub('?', indice <= 3 ? indice.to_s : '_')
		else
			return code
		end
	end

	def self.for_select
		{
		  'Formations catalogue' => where(hors_catalogue:false).map { |i| i.nom },
		  'Formations hors catalogue' => where(hors_catalogue:true).map { |i| i.nom }
		}
	end

	def positive_color
		if self.color == '#000000'
			'#FBFBFB'
		else
			self.color
		end
	end

end

app/controllers/formations_controller.rb
# ENCODING: UTF-8

class FormationsController < ApplicationController
  before_action :set_formation, only: [:show, :edit, :update, :destroy]
  before_action :is_user_authorized

  # GET /formations
  # GET /formations.json
  def index
    params[:nom] ||= session[:nom]  # ???? 
    params[:catalogue] ||= 'yes'
    params[:paginate] ||= 'pages'
    params[:column] ||= session[:column]
    params[:direction_formations] ||= session[:direction_formations]
    
    unless params[:archive].blank?
      @formations = Formation.unscoped.where(archive: true)
    else
      @formations = Formation.all
    end

    unless params[:nom].blank?
      @formations = @formations.where("LOWER(nom) like :search OR LOWER(abrg) like :search OR LOWER(code_analytique) like :search", {search: "%#{params[:nom]}%".downcase})
    end

    unless params[:apprentissage].blank?
      @formations = @formations.where(apprentissage: true)
    end

    unless params[:promo].blank?
      @formations = @formations.where(promo:params[:promo])
    end

    case params[:catalogue]
    when 'yes'
      @formations = @formations.where(hors_catalogue: false)
    when 'no'
      @formations = @formations.where(hors_catalogue: true)
    when 'all'
    end

    session[:nom] = params[:nom] # ???? 
    session[:column] = params[:column]
    session[:direction_formations] = params[:direction_formations]

    @formations = @formations.reorder("#{sort_column} #{sort_direction}") 
    
    @all_formations = @formations
    if params[:paginate] == 'pages'
       @formations = @formations.paginate(page: params[:page], per_page: 10)
    end

    @diplomes = Formation.where.not(diplome: nil).select(:diplome).uniq.pluck(:diplome).sort
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
    @salles_habituelles = @formation.cours
                                    .joins(:salle)
                                    .where("salles.bloc != 'Z'")
                                    .select('cours.id')
                                    .group(:salle_id)
                                    .count(:id)
                                    .sort_by{|k, v| v}
                                    .reverse
                                    .first(5)

    @average_count = 0
    @salles_habituelles.map{|x| @average_count += x.last.to_i / 5}
  end

  # GET /formations/new
  def new
    @formation = Formation.new
    15.times { @formation.unites.build }
    10.times { @formation.etudiants.build } 
    10.times { @formation.vacations.build }
  end

  # GET /formations/1/edit
  def edit
    5.times { @formation.unites.build }
    5.times { @formation.etudiants.build } 
    10.times { @formation.vacations.build }
  end

  # POST /formations
  # POST /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to @formation, notice: 'Formation ajoutée' }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation modifiée' }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_path, notice: 'Formation supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.unscoped.find(params[:id])
    end

    def sortable_columns
      ['formations.nom', 'formations.abrg','formations.nbr_etudiants','formations.code_analytique']
    end

    def sort_column
        sortable_columns.include?(params[:column]) ? params[:column] : 'nom'
    end

    def sort_direction
        %w[asc desc].include?(params[:direction_formations]) ? params[:direction_formations] : 'asc'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params.require(:formation)
            .permit(:nom, :promo, :diplome, :domaine, :apprentissage, :memo, :nbr_etudiants, :nbr_heures, 
                    :abrg, :user_id, :color, :Forfait_HETD, :hors_catalogue, :nomtauxtd, :code_analytique, :catalogue, :archive, :hss, :courriel,
                    unites_attributes: [:id, :code, :nom, :séances, :heures, :destroy],
                    etudiants_attributes: [:id, :nom, :prénom, :email, :mobile, :_destroy],
                    vacations_attributes: [:id, :date, :intervenant_id, :titre, :qte, :forfaithtd, :commentaires, :_destroy])
    end

    def is_user_authorized
      authorize Formation
    end
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/views/formations/_formation.html.erb
<% formation_cours = formation.cours %>
<% formation_cours_planifié_count = formation_cours.planifié.count %>

<tr class=<%= formation_cours_planifié_count != 0 ? 'warning' : '' %>>
    <td>
        <span style="background-color:<%= formation.color %>;padding-left: 5px;"></span>
        <span style="padding-left: 10px;"></span>
        <%= link_to formation.nom, formation %>
    </td>
    <td><%= formation.abrg %></td>
    <td><%= formation.nbr_etudiants %></td>
    <td><%= formation.code_analytique %></td>
    <td>
        <%= link_to_unless formation_cours_planifié_count.zero?, formation_cours_planifié_count, cours_path(ids:formation_cours.planifié.pluck(:id)) %>
    </td>
    <td>
        <% formation_cours_confirmé_count = formation_cours.confirmé.count %>
        <%= link_to_unless (formation.archive || formation_cours_confirmé_count.zero?), formation_cours_confirmé_count, cours_path(ids:formation_cours.confirmé.pluck(:id), filter:'all') %>
    </td>
    <td>
        <% formation_cours_réalisé_count = formation_cours.réalisé.count %>
        <%= link_to_unless (formation.archive || formation_cours_réalisé_count.zero?), formation_cours_réalisé_count, cours_path(ids:formation_cours.réalisé.pluck(:id), filter:'all') %>
    </td>
    <td>
        <%= link_to edit_formation_path(formation), class: "btn btn-default" do %>
            <%= fa_icon 'edit' %>
        <% end %>
    </td>
    <td>
        <% unless formation_cours.any? %>
            <%= link_to(formation, method: :delete, data:{confirm: 'Confirmez-vous ?'}, class: "btn btn-default") do %>
                <%= fa_icon 'trash-alt' %>
            <% end %>
        <% end %>
    </td>
</tr>

app/views/formations/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
	<div class="btn-group float-right">
		<%= link_to @formation, class: 'btn btn-sm btn-outline-primary' do %>
			<%= fa_icon 'eye' %> Voir
		<% end %>

		<%= link_to '#UE', data: {'toggle':'collapse'}, class: 'btn btn-sm btn-outline-primary' do %>
			<%= fa_icon 'book' %> UE
		<% end %>

		<%= link_to '#Etudiants', data: {'toggle':'collapse'}, class: 'btn btn-sm btn-outline-primary' do %>
			<%= fa_icon 'graduation-cap' %> Etudiants
		<% end %>

		<%= link_to '#Vacations', data: {'toggle':'collapse'}, class: 'btn btn-sm btn-outline-primary' do %>
			<%= fa_icon 'user-md' %> Vacations
		<% end %>

		<%= link_to formations_path, class: 'btn btn-sm btn-outline-primary' do %>
			<%= fa_icon 'list' %> Retour
		<% end %>

	</div>
  	<h3><%= fa_icon 'briefcase' %> Modification d'une formation</h3>
</div>

<%= render 'form' %>

app/views/formations/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <% if policy(Formation).new? %>
    <%= link_to new_formation_path, class: 'btn text-primary float-right' do %>
      <%= fa_icon 'plus-circle' %> Formation
    <% end %>
  <% end %>
  <h3><%= fa_icon 'briefcase' %> Liste des formations</h3>
</div>

<div class="container-fluid p-3 shadow-sm">
    <%= form_tag request.path, method: :get do %>
      <div class="form-group">
        <div class="row">

          <div class="col-sm-5">
            <%= label_tag :nom, "Nom/Abrg./Code/Promo" %>
            <div class="input-group">    
              <%= text_field_tag :nom, params[:nom], include_blank:true, onchange:'this.form.submit()', class:"form-control form-control-sm" %>
              <span class="input-group-btn">
                  <%= submit_tag 'Filtrer', class:"btn btn-sm btn-success" %>
              </span>
            </div> 
          </div>

          <div class="col-sm-3">
            <%= label_tag :catalogue, "Catalogue ?" %>
            <br>
            <%= radio_button_tag :catalogue, "yes", (params[:catalogue]=='yes'), onchange:'this.form.submit()' %>
            Oui 
            <%= radio_button_tag :catalogue, "no", (params[:catalogue]=='no'), onchange:'this.form.submit()' %>
            Non 
            <%= radio_button_tag :catalogue, "all", (params[:catalogue]=='all'), onchange:'this.form.submit()' %>
            Tout           
          </div>

          <div class="col-sm-2">
            <%= label_tag :archive, "Archivées ?" %>
            <br>
            <%= check_box_tag :archive, 1, params[:archive], onchange:'this.form.submit()' %>
          </div>

          <div class="col-sm-2">
              <%= label_tag "Afficher" %>
              <br> 
              <%= radio_button_tag :paginate, "pages", (params[:paginate]=='pages'), onchange:'this.form.submit()' %>
              Pages 
              <%= radio_button_tag :paginate, "all", (params[:paginate]=='all'), onchange:'this.form.submit()' %>
              Tout 
          </div>
          
        </div>
      </div>  
    <% end %>
</div>
<br>

<% if @formations.any? %>
  <div class="table-responsive">
    <table class="table table-hover table-striped table-bordered">
      <thead>
        <tr>
          <th><%= sort_link 'formations.nom', 'Nom' %></th>
          <th><%= sort_link 'formations.abrg', 'Abrg.' %></th>
          <th><%= sort_link 'formations.nbr_etudiants', 'Etudiants' %></th>
          <th><%= sort_link 'formations.code_analytique', 'Code' %></th>
          <th>Planifiés</th>
          <th>Confirmés</th>
          <th>Réalisés</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tfoot>
        <tr>
          <th colspan=9></th>
        </tr>
      </tfoot>

      <tbody>
        <%= render @formations.includes(:cours) %>
      </tbody>

    </table>

    <% if params[:paginate] == 'pages' %>
      <div class="page_info">
        <%= page_entries_info @formations %>
      </div>

      <%= will_paginate @formations, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <% end %>  
  </div>
<% end %>

app/views/formations/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h3><%= fa_icon 'briefcase' %> Nouvelle formation</h3>
</div>

<%= render 'form' %>

app/views/formations/show.html.erb
<div class="card shadow-sm p-3 mt-3">
  <div>
    <div class="btn-group float-right">
      <% if policy(@formation).edit? %>
        <%= link_to edit_formation_path(@formation), class: 'btn btn-sm btn-outline-primary' do %>
          <%= fa_icon 'edit' %> Modifier
        <% end %>
      <% end %>

      <a href="#audit" data-toggle="collapse" class='btn btn-sm btn-outline-primary'>
        <%= fa_icon 'search' %> Audit
      </a>

      <%= link_to formations_path, class: 'btn btn-sm btn-outline-primary' do %>
        <%= fa_icon 'list' %> Retour
      <% end %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-sm-1">
      <h2>
        <span style="opacity: 80%;color:<%= @formation.color %>">
          <%= fa_icon 'briefcase 2x' %>
        </span>
      </h2>
    </div>    

    <div class="col-sm-6">
      <h3>
        <small class="text-muted">Nom</small><br>
        <%= @formation.nom %>
      </h3>
      
      <% if @formation.archive %>
        <p><mark>FORMATION ARCHIVEE !</mark></p>
        <br>
      <% end %>

      <% if @formation.apprentissage %>
        <p><mark>Apprentissage</mark></p>
      <% end %>
      
      <% if @formation.hors_catalogue %>
        <p><mark>Hors catalogue</mark></p>
      <% end %>

      <% if @formation.hss? %>
        <p><mark>Hors états de services</mark></p>
      <% end %>

      <br>

      <h3>
        <small class="text-muted">Promo</small><br>
        <%= @formation.promo %>
      </h3>
    </div>

    <div class="col-sm-4">
      <h3>
        <small class="text-muted">Abrégé</small><br>
        <%= @formation.try(:abrg) %>
      </h3>
      <br> 
      <h4>
        <small class="text-muted">Gestionnaire de formation</small><br>
        <%= @formation.try(:user).try(:email) %>
      </h4>
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-sm-3">
      <h3>
        <small class="text-muted">Diplôme</small><br>
      </h3>
      <p>
        <%= @formation.diplome %>
      </p>

      <h3>
        <small class="text-muted">Heures prévues</small><br>
      </h3>
      <%= @formation.nbr_heures %>
    </div>

    <div class="col-sm-4">
      <h3>
        <small class="text-muted">Code Analytique</small><br>
      </h3>
      <p>
        <%= @formation.code_analytique %>
      </p>

      <h3>
        <small class="text-muted">Taux Horaire</small><br>
      </h3>
      <%= @formation.nomtauxtd %>
    </div>

    <div class="col-sm-5">
      <h3>
        <small class="text-muted">Nbr Etudiants</small>
      </h3>
      <p>
        Estimé : <%= @formation.nbr_etudiants %>
        |
        Enregistré : <%= @formation.etudiants.size %>
      </p>
      <h3>
        <small class="text-muted">Salles habituelles</small><br>
      </h3>
      <% @salles_habituelles.each do |salle_id, count| %>
        <% salle = Salle.find(salle_id) %>
        <span class="badge badge-sm badge-pill badge-success" style="font-size: calc( .25rem + <%= [1.5, (count.fdiv(@average_count))].min %>rem);" title="Salle <%= salle.nom %> a été utilisée <%= count %> fois">
          <%= salle.nom.first(2) %>
        </span>
      <% end %>
    </div>
  </div>

  <% if @formation.unites.any? %>
    <h3>
      <small class="text-muted">Unités d'enseignements</small>
    </h3>
    
    <div class="table-responsive">
      <table class="table table-striped table-hover table-sm">
        <thead>
          <tr>
            <th>Code</th>
            <th>Intitulé</th>
            <th>Séances prévues</th>
            <th>Séances réalisées</th>
            <th>Heures prévues</th>
            <th>Heures réalisées</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% total_ue_prévu = total_prévu = 0.0 %>
          <% total_ue_réalisé = total_réalisé = 0.0 %>
          <% @formation.unites.each do | unite | %>
            <tr>
              <% cours = @formation.cours.where(code_ue: unite.code) %>
              <td style="text-align: right;"><%= link_to unite.code, cours_path(formation_id: @formation, ue: unite.num) %></td>
              <td><%= unite.nom %></td>
              <td style="text-align: right;"><%= unite.séances %></td>
              <td style="text-align: right;"><%= link_to cours.count, cours_path(formation_id: @formation, ue: unite.num, filter: 'all') %></td>
              <td style="text-align: right;">
                <%= total_prévu = unite.heures %> h
              </td>
              <td style="text-align: right;">
                <%= total_réalisé = cours.sum(:duree) %> h
              </td>
              <td>
                <% if unite && (total_réalisé > 0 && unite.heures > 0) %>
                  (<%= ((total_réalisé * 100) / unite.heures).round %>%)
                <% end %>
              </td>
              <% total_ue_prévu += total_prévu %>
              <% total_ue_réalisé += total_réalisé %>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
          <tr>
            <th colspan=4></th>
            <th style="text-align: right;"><%= total_ue_prévu %> h</th>
            <th style="text-align: right;"><%= total_ue_réalisé %> h</th>
            <th></th>
          </tr>
        </tfoot>  
      </table>
    </div>
  <% end %>

  <% if @formation.etudiants.any? %>
    <h3>
      <small class="text-muted">Etudiants</small>
    </h3>
    
    <div class="table-responsive">
      <table class="table table-striped table-hover table-sm">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Mobile</th>
          </tr>
        </thead>

        <tbody>
          <% @formation.etudiants.each do | etudiant | %>
            <tr>
              <td><%= etudiant.nom %></td>
              <td><%= etudiant.prénom %></td>
              <td><%= etudiant.email %></td>
              <td><%= etudiant.mobile %></td>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
          <tr>
            <th></th><th></th><th></th><th></th>
          </tr>
        </tfoot>  
      </table>
    </div>
  <% end %>

  <% if @formation.vacations.any? %>
    <h3>
      <small class="text-muted">Vacations</small>
    </h3>

    <table class="table table-striped table-hover table-sm">
      <thead>
        <th>Date</th>
        <th>Formation</th>
        <th>Activité</th>
        <th>Intervenant</th>
        <th>Qté</th>
        <th>Forfait HTD</th>
        <th>Commentaires</th>
      </thead>

      <% @formation.vacations.each do |vacation| %>
        <%= render vacation %>
      <% end %>
    </table>
  <% end %>

  <div id="audit" class="collapse">
    <% if @formation.audits.any? %>
      <h4>Audit des modifications</h4>
      <table class="table table-bordered table-hover table-condensed">
        <thead>
          <th>Date</th>
          <th>Utilisateur</th>            
          <th>Type</th>
          <th>Record_id</th>
          <th>Action</th>
          <th>Modifications</th>
        </thead>

        <%= render partial: 'tools/audit', collection: @formation.audits %>

      </table>
    <% end %>
  </div> 
</div>